import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function HomePage () {
    return (
        <div className={styles.container}>
            <Head>
                <title>Welcome to Nelson&apos;s personal website</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                Hi, I am Nelson Kshetrimayum
                </h1>

                <p className={styles.description}>
                Pursuing<br/> <b>Integrated M.Sc.</b><br/> at<br/> <b>National Institue of Science Education and Research, Bhubaneswar</b>
                </p>

            </main>

            <footer className={styles.footer}>
                <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
                >
                Powered by{' '}
                <span className={styles.logo}>
                    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </span>
                </a>
            </footer>
        </div>
    )
}